# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hypertunnel < Formula
  desc "P2P file transfer tool using WebRTC"
  homepage "https://github.com/abrekhov/hypertunnel"
  version "0.0.3-SNAPSHOT-84c7ff7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abrekhov/hypertunnel/releases/download/v0.0.3/ht_darwin_amd64"
      sha256 "8dd03dd43485418aff1aa610ab8c8683138f42ba8d8d73699634af6715362b11"

      def install
        bin.install "ht"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abrekhov/hypertunnel/releases/download/v0.0.3/ht_darwin_arm64"
      sha256 "e26ef8166b8065740507d0eabb8813324eb7d734cde07c61bf8aa032668bdf49"

      def install
        bin.install "ht"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/abrekhov/hypertunnel/releases/download/v0.0.3/ht_linux_amd64"
      sha256 "eee66c2e4a8d24164f6962dc510e88c67f929d8f8841e5f0dc4dd0e4e27ea256"
      def install
        bin.install "ht"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/abrekhov/hypertunnel/releases/download/v0.0.3/ht_linux_arm64"
      sha256 "6db949ffd38fb011ed88df943e62ac967955dee6776d95e88b8f19aa387634b2"
      def install
        bin.install "ht"
      end
    end
  end

  test do
    system "#{bin}/ht", "--help"
  end
end
